In [48]:
import pandas as pd
import numpy as np

In [49]:
data = pd.read_csv('data/data_all.csv')

In [50]:
data.head()

,Unnamed: 0,Address,Price,Space,Rooms,Market,Year,Evelevator,Balcony,Level,Parking place
0,0,"Warszawa, Białołęka, Żerań, ul. Starowiślna",565000.0,41.34,2,wtórny,2019,tak,"ogródek, taras",parter/6,garaż/miejsce parkingowe
1,1,"Warszawa, Ursynów, Wyczółki",575000.0,43.52,2,wtórny,2021,tak,balkon,4/4,NaN
2,2,"Warszawa, Śródmieście, Śródmieście Północne, u...",744000.0,37.4,2,wtórny,2011,tak,balkon,2/6,garaż/miejsce parkingowe
3,3,"Warszawa, Białołęka, ul. Leona Berensona",444845.0,56.8,3,pierwotny,2021,tak,balkon,NaN,garaż/miejsce parkingowe
4,4,"Warszawa, Praga-Południe, Saska Kępa, ul. Zako...",1700000.0,91.5,4,wtórny,1939,nie,"balkon, ogródek",1/3,NaN

## Price

### Too big values

In [51]:
data[data['Price'] < 100000]

,Unnamed: 0,Address,Price,Space,Rooms,Market,Year,Evelevator,Balcony,Level,Parking place
13721,2021,"Warszawa, Bemowo, ul. Lazurowa",25000.0,30.55,1,wtórny,nie,NaN,NaN,1,garaż/miejsce parkingowe
16395,795,"Warszawa, Mokotów, Służewiec, ul. Wróbla",36000.0,11.5,1,wtórny,1999,nie,NaN,parter/3,NaN

In [52]:
price_z = (data.Price - data.Price.mean()) / data.Price.std()
print(len(price_z[price_z> 3]))
print(len(price_z[price_z< -3]))

158
0

In [53]:
data.Price[price_z[price_z> 3].index].min()

55278950.0

In [54]:
data.Price[price_z[price_z> 3].index].max()

904581046.0

In [55]:
data.Price[price_z[price_z> 3].index].index

Int64Index([  590,   591,   603,   611,   639,   661,   668,   671,   672,
              678,
            ...
            19000, 19018, 19815, 19884, 19901, 20122, 21180, 21181, 21324,
            23174],
           dtype='int64', length=158)

In [56]:
data.drop(data.Price[price_z[price_z> 3].index].index, inplace= True)

In [57]:
data.sort_values('Price',ascending=False, inplace=True)
data.head(60)

,Unnamed: 0,Address,Price,Space,Rooms,Market,Year,Evelevator,Balcony,Level,Parking place
17988,2388,"Warszawa, Białołęka, Kąty Grodziskie",55091050.0,55.93,2,pierwotny,2022-03-06,plastikowe,balkon,2/2,NaN
11849,149,"Warszawa, Wawer",54842670.0,60.39,3,pierwotny,2023,tak,balkon,parter/5,garaż/miejsce parkingowe
2348,2348,"Warszawa, Białołęka, ul. Płochocińska",54663150.0,63.43,3,pierwotny,2023,tak,balkon,1/2,garaż/miejsce parkingowe
2431,2431,"Warszawa, Białołęka, ul. Płochocińska",54644650.0,63.43,3,pierwotny,2023,tak,balkon,1/2,garaż/miejsce parkingowe
6417,2517,"Warszawa, Białołęka, Leona Berensona",54454950.0,52.11,3,pierwotny,2022,NaN,balkon,2/2,garaż/miejsce parkingowe
19017,3417,"Warszawa, Bemowo",53892720.0,35.95,2,wtórny,nie,NaN,balkon,5/5,garaż/miejsce parkingowe
18281,2681,"Warszawa, Białołęka, Kąty Grodziskie",53412750.0,52.11,2,pierwotny,2022-03-06,plastikowe,balkon,2/2,NaN
13641,1941,"Warszawa, Ursynów, rtm. Witolda Pileckiego",52351137.0,32.49,2,pierwotny,2022-10-01,tak,NaN,3/5,garaż/miejsce parkingowe
19899,4299,"Warszawa, Bemowo, Jeździecka",52124040.0,36.06,2,pierwotny,2024-01-10,nie,balkon,3/6,NaN
6375,2475,"Warszawa, Białołęka, ul. Ostródzka",51675350.0,57.43,3,pierwotny,2024,tak,balkon,parter/3,garaż/miejsce parkingowe
6377,2477,"Warszawa, Białołęka, ul. Ostródzka",51675350.0,57.43,3,pierwotny,2024,tak,balkon,parter/3,garaż/miejsce parkingowe
18843,3243,"Warszawa, Bemowo",51395760.0,36.93,2,pierwotny,2024,NaN,balkon,3/5,NaN
13624,1924,"Warszawa, Ursynów, rtm. Witolda Pileckiego",51062097.0,31.69,2,pierwotny,2022-10-01,cegła,NaN,3/8,garaż/miejsce parkingowe
8322,522,"Warszawa, Ursynów",50965419.0,31.63,2,pierwotny,2022,monitoring / ochrona,balkon,4/4,garaż/miejsce parkingowe
14031,2331,"Warszawa, Ursynów, rtm. Witolda Pileckiego",50965419.0,31.63,2,pierwotny,2022-10-01,tak,NaN,3/5,garaż/miejsce parkingowe
9563,1763,"Warszawa, Bemowo, Chrzanów, Szeligowska",50958180.0,35.94,2,pierwotny,2024,tak,ogródek,parter/5,garaż/miejsce parkingowe
13900,2200,"Warszawa, Bemowo, Szeligowska",50958180.0,35.94,2,pierwotny,2024,NaN,ogródek,parter/5,garaż/miejsce parkingowe
7707,3807,"Warszawa, Włochy",50863840.0,45.71,2,pierwotny,2022,tak,balkon,3,garaż/miejsce parkingowe
6074,2174,"Warszawa, Włochy",50676160.0,45.54,2,pierwotny,2022,tak,balkon,3,garaż/miejsce parkingowe
18019,2419,"Warszawa, mazowieckie",48621544.0,37.06,2,pierwotny,apartamentowiec,NaN,balkon,2/4,garaż/miejsce parkingowe
11584,3784,"Warszawa, mazowieckie",48621544.0,37.06,2,pierwotny,apartamentowiec,NaN,balkon,2/4,garaż/miejsce parkingowe
15015,3315,"Warszawa, mazowieckie",48621544.0,37.06,2,pierwotny,apartamentowiec,NaN,balkon,2/4,garaż/miejsce parkingowe
4728,828,"Warszawa, mazowieckie",48621544.0,37.06,2,pierwotny,apartamentowiec,NaN,balkon,2/4,garaż/miejsce parkingowe
5968,2068,"Warszawa, mazowieckie",48621544.0,37.06,2,pierwotny,apartamentowiec,NaN,balkon,2/4,garaż/miejsce parkingowe
5032,1132,"Warszawa, mazowieckie",48621544.0,37.06,2,pierwotny,apartamentowiec,NaN,balkon,2/4,garaż/miejsce parkingowe
1583,1583,"Warszawa, Białołęka, Leona Berensona",48465560.0,59.54,4,pierwotny,2024,nie,balkon,1/2,garaż/miejsce parkingowe
4979,1079,"Warszawa, Białołęka, Leona Berensona",48393450.0,51.21,2,pierwotny,2024,nie,balkon,1/2,garaż/miejsce parkingowe
1586,1586,"Warszawa, Białołęka, Kąty Grodziskie",47920356.0,52.11,3,pierwotny,2022,nie,balkon,2/2,garaż/miejsce parkingowe
19829,4229,"Warszawa, Praga-Południe",47687720.0,36.91,2,pierwotny,2023,NaN,NaN,parter/4,NaN
13817,2117,"Warszawa, Praga-Południe",45160645.0,32.26,1,pierwotny,2022-04-20,plastikowe,balkon,1/4,garaż/miejsce parkingowe
16231,631,"Warszawa, Ochota",39897717.0,32.17,1,pierwotny,apartamentowiec,"drzwi / okna antywłamaniowe, domofon / wideofon",NaN,4/5,NaN
5229,1329,"Warszawa, Białołęka, ul. Leona Berensona",36848850.0,37.41,2,pierwotny,2023,nie,balkon,1/2,garaż/miejsce parkingowe
10138,2338,"Warszawa, Ursynów, rtm. Witolda Pileckiego",35900010.0,20.7,1,pierwotny,2022-10-01,cegła,NaN,3/8,garaż/miejsce parkingowe
2267,2267,"Warszawa, Białołęka, ul. Płochocińska",32448050.0,35.79,1,pierwotny,2023,tak,balkon,2/2,garaż/miejsce parkingowe
2281,2281,"Warszawa, Białołęka, ul. Płochocińska",32448050.0,35.79,1,pierwotny,2023,tak,balkon,2/2,garaż/miejsce parkingowe
2252,2252,"Warszawa, Białołęka, ul. Płochocińska",32443050.0,35.79,1,pierwotny,2023,tak,balkon,2/2,garaż/miejsce parkingowe
1582,1582,"Warszawa, Białołęka, Leona Berensona",32426988.0,37.41,2,pierwotny,2024,nie,balkon,1/2,garaż/miejsce parkingowe
1585,1585,"Warszawa, Białołęka, Leona Berensona",32305636.0,37.27,2,pierwotny,2024,nie,balkon,2/2,garaż/miejsce parkingowe
2389,2389,"Warszawa, Białołęka, ul. Płochocińska",32036650.0,35.79,1,pierwotny,2023,tak,balkon,parter/2,garaż/miejsce parkingowe
2401,2401,"Warszawa, Białołęka, ul. Płochocińska",32036650.0,35.79,1,pierwotny,2023,tak,balkon,parter/2,garaż/miejsce parkingowe
2363,2363,"Warszawa, Białołęka, ul. Płochocińska",32036650.0,35.79,1,pierwotny,2023,tak,balkon,parter/2,garaż/miejsce parkingowe
2362,2362,"Warszawa, Białołęka, ul. Płochocińska",32036650.0,35.79,1,pierwotny,2023,tak,balkon,parter/2,garaż/miejsce parkingowe
17955,2355,"Warszawa, Ursynów, rtm. Witolda Pileckiego",32015178.0,18.46,1,pierwotny,2022-12-31,tak,balkon,1/4,NaN
11024,3224,"Warszawa, Ursynów, rtm. Witolda Pileckiego",31963149.0,18.43,1,pierwotny,2022-10-01,tak,NaN,1/5,garaż/miejsce parkingowe
13633,1933,"Warszawa, Ursynów",31963149.0,18.43,1,pierwotny,2022,monitoring / ochrona,balkon,3/4,garaż/miejsce parkingowe
15809,209,"Warszawa, Ursynów, rtm. Witolda Pileckiego",31755033.0,18.31,1,pierwotny,2022-10-01,tak,balkon,3/5,garaż/miejsce parkingowe
19388,3788,"Warszawa, Ursynów, Pyry",29465757.0,16.99,1,pierwotny,nie,NaN,NaN,3/3,NaN
10137,2337,"Warszawa, Ursynów, rtm. Witolda Pileckiego",29465757.0,16.99,1,pierwotny,2022-10-01,cegła,NaN,3/8,garaż/miejsce parkingowe
18274,2674,"Warszawa, Ursynów, rtm. Witolda Pileckiego",29396385.0,16.95,1,pierwotny,2022-12-31,tak,balkon,3/4,NaN
18143,2543,"Warszawa, Ursynów",29396385.0,16.95,1,pierwotny,nie,NaN,NaN,4/4,NaN
15847,247,"Warszawa, Ursynów, rtm. Witolda Pileckiego",29396385.0,16.95,1,pierwotny,2022-10-01,tak,balkon,3/5,garaż/miejsce parkingowe
9953,2153,"Warszawa, Wola, Odolany, Apartamentowiec. Powr...",28463659.0,18.36,1,pierwotny,2022-08-01,plastikowe,balkon,4/24,garaż/miejsce parkingowe
16202,602,"Warszawa, Śródmieście, Powiśle, Elektryczna",21350100.0,487.75,10,wtórny,2021,tak,taras,6/6,garaż/miejsce parkingowe
12380,680,"Warszawa, Śródmieście, Powiśle",20400000.0,488.0,6,wtórny,2021,NaN,NaN,6/6,NaN
2504,2504,"Warszawa, Mokotów, Cybulskiego",19900000.0,487.0,6,wtórny,2001,tak,taras,5/5,garaż/miejsce parkingowe
6136,2236,"Warszawa, Śródmieście, Złota",15900000.0,208.4,5,wtórny,blok,pom. użytkowe,NaN,&gt; 10/52,garaż/miejsce parkingowe
19806,4206,"Warszawa, Śródmieście, Śródmieście Północne, N...",15671000.0,344,6,wtórny,2009,tak,balkon,1/7,garaż/miejsce parkingowe
6128,2228,"Warszawa, Śródmieście, Niecała",15671000.0,344.0,7,wtórny,apartamentowiec,inne,NaN,1/7,NaN
14162,2462,"Warszawa, Śródmieście, Powiśle, Drewniana",14000000.0,237.0,5,wtórny,2011,tak,balkon,5/5,garaż/miejsce parkingowe
20175,4575,"Warszawa, Śródmieście, Powiśle",13700000.0,357.1,4,wtórny,2021,NaN,NaN,5/6,NaN

Biggest price values seems to be wrong. 55 milinos for 55 square meters is unreasonable. I'm going to drop those values.

In [58]:
big_values_index = data[data['Price']>= 28463659.0].index	
data.drop(big_values_index,inplace=True)

### Missing values

In [59]:
data.Price.isna().sum()

6042

In [60]:
data.dropna(subset = ['Price'], axis = 'rows',inplace=True)

In [61]:
data.Price.isna().sum()

0

### Small values

In [62]:
data.tail(20)

,Unnamed: 0,Address,Price,Space,Rooms,Market,Year,Evelevator,Balcony,Level,Parking place
20117,4517,"Warszawa, Targówek",210000.0,72.51,3,wtórny,2005,tak,"balkon, taras",4/4,NaN
9117,1317,"Warszawa, Praga-Południe",204000.0,25.6,1,wtórny,2022-07-08,tak,NaN,suterena/5,garaż/miejsce parkingowe
23080,7480,"Warszawa, Mokotów",200000.0,65,2,wtórny,2001,tak,NaN,10/10,garaż/miejsce parkingowe
22243,6643,"Warszawa, Mokotów, Rakowiecka",200000.0,73,2,wtórny,2001,tak,NaN,10/10,garaż/miejsce parkingowe
11304,3504,"Warszawa, Ursus",199000.0,14.0,1,pierwotny,2023,cegła,NaN,1/2,NaN
2051,2051,"Warszawa, Mokotów, ul. Stefana Batorego",199000.0,15.0,1,wtórny,nie,NaN,NaN,parter,NaN
21426,5826,"Warszawa, Śródmieście, Grzybowska",196803.0,46.62,2,wtórny,2009,tak,balkon,2/22,NaN
13532,1832,"Warszawa, Targówek",190000.0,14.3,1,pierwotny,2022,system alarmowy,NaN,parter/2,garaż/miejsce parkingowe
13567,1867,"Warszawa, Targówek",190000.0,14.3,1,wtórny,2022,system alarmowy,NaN,2/2,garaż/miejsce parkingowe
3454,3454,"Warszawa, Targówek",190000.0,14.3,1,pierwotny,2022,silikat,NaN,1/2,NaN
21425,5825,"Warszawa, Śródmieście, Grzybowska",184308.0,43.66,2,wtórny,2009,tak,balkon,3/22,NaN
4501,601,"Warszawa, Włochy, Zdobnicza",173621.0,14.59,1,wtórny,2022-09-30,nie,NaN,1/3,garaż/miejsce parkingowe
7852,52,"Warszawa, Praga-Południe, Kamionek, ul. Mińska",169000.0,36.2,1,wtórny,2003,tak,balkon,3/7,NaN
2686,2686,"Warszawa, Wola, Wawrzyszewska",146000.0,39.0,2,wtórny,2022-05-06,plastikowe,balkon,7/7,garaż/miejsce parkingowe
11303,3503,"Warszawa, Ursus",145000.0,10.0,1,wtórny,2021,cegła,NaN,suterena/3,NaN
16174,574,"Warszawa, Rembertów, Zawodowa",139000.0,30.5,1,wtórny,1955,nie,NaN,parter/1,NaN
13536,1836,"Warszawa, Targówek",130000.0,8.9,1,pierwotny,2022,system alarmowy,NaN,2/2,garaż/miejsce parkingowe
5740,1840,"Warszawa, Targówek",130000.0,8.9,1,wtórny,2022,silikat,NaN,1/2,garaż/miejsce parkingowe
16395,795,"Warszawa, Mokotów, Służewiec, ul. Wróbla",36000.0,11.5,1,wtórny,1999,nie,NaN,parter/3,NaN
13721,2021,"Warszawa, Bemowo, ul. Lazurowa",25000.0,30.55,1,wtórny,nie,NaN,NaN,1,garaż/miejsce parkingowe

I wiil drop just four lowest values.

In [63]:
small_values_index = data[data['Price']<= 130000.0].index	
data.drop(small_values_index,inplace=True)

In [64]:
data.tail(10)

,Unnamed: 0,Address,Price,Space,Rooms,Market,Year,Evelevator,Balcony,Level,Parking place
21426,5826,"Warszawa, Śródmieście, Grzybowska",196803.0,46.62,2,wtórny,2009,tak,balkon,2/22,NaN
13532,1832,"Warszawa, Targówek",190000.0,14.3,1,pierwotny,2022,system alarmowy,NaN,parter/2,garaż/miejsce parkingowe
13567,1867,"Warszawa, Targówek",190000.0,14.3,1,wtórny,2022,system alarmowy,NaN,2/2,garaż/miejsce parkingowe
3454,3454,"Warszawa, Targówek",190000.0,14.3,1,pierwotny,2022,silikat,NaN,1/2,NaN
21425,5825,"Warszawa, Śródmieście, Grzybowska",184308.0,43.66,2,wtórny,2009,tak,balkon,3/22,NaN
4501,601,"Warszawa, Włochy, Zdobnicza",173621.0,14.59,1,wtórny,2022-09-30,nie,NaN,1/3,garaż/miejsce parkingowe
7852,52,"Warszawa, Praga-Południe, Kamionek, ul. Mińska",169000.0,36.2,1,wtórny,2003,tak,balkon,3/7,NaN
2686,2686,"Warszawa, Wola, Wawrzyszewska",146000.0,39.0,2,wtórny,2022-05-06,plastikowe,balkon,7/7,garaż/miejsce parkingowe
11303,3503,"Warszawa, Ursus",145000.0,10.0,1,wtórny,2021,cegła,NaN,suterena/3,NaN
16174,574,"Warszawa, Rembertów, Zawodowa",139000.0,30.5,1,wtórny,1955,nie,NaN,parter/1,NaN

## Space

In [65]:
data.Space = data.Space.str.replace('/','')
data.Space = data.Space.astype('float')

### Big values

In [66]:
data.sort_values('Space',ascending=False, inplace=True)
data.head(20)

,Unnamed: 0,Address,Price,Space,Rooms,Market,Year,Evelevator,Balcony,Level,Parking place
8686,886,"Warszawa, Praga-Północ, ul. Inżynierska",1500000.0,919.45,4,wtórny,1929,domofon / wideofon,balkon,4/4,NaN
14362,2662,"Warszawa, Praga-Południe",5520000.0,600.00,10,wtórny,kamienica,"telewizja kablowa, internet, telefon","balkon, ogródek, taras",3/3,garaż/miejsce parkingowe
20970,5370,"Warszawa, Wawer, ul. Patriotów",4000000.0,560.00,4,wtórny,2015,tak,"balkon, ogródek, taras",3/3,garaż/miejsce parkingowe
7155,3255,"Warszawa, Wawer, ul. Patriotów",4000000.0,560.00,4,wtórny,2015,tak,"balkon, ogródek, taras",3/3,garaż/miejsce parkingowe
1687,1687,"Warszawa, Wilanów, Sarmacka",7600000.0,497.00,8,wtórny,2005,nie,"balkon, ogródek, taras",NaN,garaż/miejsce parkingowe
12380,680,"Warszawa, Śródmieście, Powiśle",20400000.0,488.00,6,wtórny,2021,NaN,NaN,6/6,NaN
16202,602,"Warszawa, Śródmieście, Powiśle, Elektryczna",21350100.0,487.75,10,wtórny,2021,tak,taras,6/6,garaż/miejsce parkingowe
2504,2504,"Warszawa, Mokotów, Cybulskiego",19900000.0,487.00,6,wtórny,2001,tak,taras,5/5,garaż/miejsce parkingowe
9677,1877,"Warszawa, Praga-Południe, Gocław",795900.0,445.00,2,pierwotny,2022,tak,"balkon, taras",4/8,garaż/miejsce parkingowe
1651,1651,"Warszawa, Mokotów",999999.0,444.00,4,pierwotny,nie,NaN,NaN,NaN,NaN
6143,2243,"Warszawa, Włochy, Nowe Włochy",4500000.0,423.00,10,wtórny,1936,nie,balkon,2/2,garaż/miejsce parkingowe
16554,954,"Warszawa, Śródmieście, Nowogrodzka",4900000.0,409.00,10,wtórny,1904,NaN,NaN,5/5,NaN
2171,2171,"Warszawa, Mokotów, Łowicka",12500000.0,400.10,7,wtórny,2005,monitoring / ochrona,NaN,7/7,garaż/miejsce parkingowe
23009,7409,"Warszawa, Bielany, ul. Hieroglif",5200000.0,390.00,5,wtórny,2021-05-29,plastikowe,taras,1/2,garaż/miejsce parkingowe
14550,2850,"Warszawa, Śródmieście, Powiśle",5490000.0,379.00,10,wtórny,apartamentowiec,NaN,NaN,1,NaN
11331,3531,"Warszawa, Śródmieście",1900000.0,367.00,4,wtórny,2002,monitoring / ochrona,NaN,&gt; 10/28,garaż/miejsce parkingowe
20175,4575,"Warszawa, Śródmieście, Powiśle",13700000.0,357.10,4,wtórny,2021,NaN,NaN,5/6,NaN
19331,3731,"Warszawa, Żoliborz, Stary Żoliborz",5950000.0,353.00,5,wtórny,2005,"system alarmowy, monitoring / ochrona","balkon, taras",5/5,garaż/miejsce parkingowe
768,768,"Warszawa, Mokotów",8483534.0,350.00,6,pierwotny,2022-07-08,aluminiowe,balkon,3/3,garaż/miejsce parkingowe
2870,2870,"Warszawa, Ursynów, Gajdy",1800000.0,350.00,10,wtórny,1995,"piwnica, pom. użytkowe","balkon, ogródek, taras",1/2,garaż/miejsce parkingowe

In [67]:
data.drop(data.index[0], axis='rows',inplace=True)

In [68]:
data.head(10)

,Unnamed: 0,Address,Price,Space,Rooms,Market,Year,Evelevator,Balcony,Level,Parking place
14362,2662,"Warszawa, Praga-Południe",5520000.0,600.00,10,wtórny,kamienica,"telewizja kablowa, internet, telefon","balkon, ogródek, taras",3/3,garaż/miejsce parkingowe
20970,5370,"Warszawa, Wawer, ul. Patriotów",4000000.0,560.00,4,wtórny,2015,tak,"balkon, ogródek, taras",3/3,garaż/miejsce parkingowe
7155,3255,"Warszawa, Wawer, ul. Patriotów",4000000.0,560.00,4,wtórny,2015,tak,"balkon, ogródek, taras",3/3,garaż/miejsce parkingowe
1687,1687,"Warszawa, Wilanów, Sarmacka",7600000.0,497.00,8,wtórny,2005,nie,"balkon, ogródek, taras",NaN,garaż/miejsce parkingowe
12380,680,"Warszawa, Śródmieście, Powiśle",20400000.0,488.00,6,wtórny,2021,NaN,NaN,6/6,NaN
16202,602,"Warszawa, Śródmieście, Powiśle, Elektryczna",21350100.0,487.75,10,wtórny,2021,tak,taras,6/6,garaż/miejsce parkingowe
2504,2504,"Warszawa, Mokotów, Cybulskiego",19900000.0,487.00,6,wtórny,2001,tak,taras,5/5,garaż/miejsce parkingowe
9677,1877,"Warszawa, Praga-Południe, Gocław",795900.0,445.00,2,pierwotny,2022,tak,"balkon, taras",4/8,garaż/miejsce parkingowe
1651,1651,"Warszawa, Mokotów",999999.0,444.00,4,pierwotny,nie,NaN,NaN,NaN,NaN
6143,2243,"Warszawa, Włochy, Nowe Włochy",4500000.0,423.00,10,wtórny,1936,nie,balkon,2/2,garaż/miejsce parkingowe

### Empty values

In [69]:
data.Space.isna().sum()

0

### Small values

In [70]:
data.tail(20)

,Unnamed: 0,Address,Price,Space,Rooms,Market,Year,Evelevator,Balcony,Level,Parking place
8929,1129,"Warszawa, Targówek, ul. Księcia Ziemowita",272000.0,17.00,1,wtórny,2022-06-01,plastikowe,NaN,3/4,NaN
7823,23,"Warszawa, Śródmieście, Mokotowska",490000.0,16.53,1,wtórny,1940,nie,NaN,1/4,garaż/miejsce parkingowe
17646,2046,"Warszawa, Śródmieście, Aleja Jana Chrystiana S...",380000.0,16.00,1,wtórny,2022-03-10,plastikowe,NaN,2/3,NaN
1607,1607,"Warszawa, Mokotów, Pole Mokotowskie, ul. Stefa...",298000.0,15.41,1,wtórny,blok,"telewizja kablowa, internet, telefon",NaN,parter/2,NaN
10781,2981,"Warszawa, Rembertów",235000.0,15.00,1,wtórny,1960,nie,NaN,parter/4,garaż/miejsce parkingowe
14024,2324,"Warszawa, Śródmieście, Nowolipie",364000.0,15.00,1,wtórny,1956,nie,NaN,parter/4,NaN
2051,2051,"Warszawa, Mokotów, ul. Stefana Batorego",199000.0,15.00,1,wtórny,nie,NaN,NaN,parter,NaN
4299,399,"Warszawa, Wola, Górczewska 6",349000.0,14.90,1,wtórny,2022-06-01,tak,NaN,2/4,NaN
4501,601,"Warszawa, Włochy, Zdobnicza",173621.0,14.59,1,wtórny,2022-09-30,nie,NaN,1/3,garaż/miejsce parkingowe
7888,88,"Warszawa, Wola",250000.0,14.40,1,wtórny,2017,tak,NaN,1/8,garaż/miejsce parkingowe
13532,1832,"Warszawa, Targówek",190000.0,14.30,1,pierwotny,2022,system alarmowy,NaN,parter/2,garaż/miejsce parkingowe
13567,1867,"Warszawa, Targówek",190000.0,14.30,1,wtórny,2022,system alarmowy,NaN,2/2,garaż/miejsce parkingowe
3454,3454,"Warszawa, Targówek",190000.0,14.30,1,pierwotny,2022,silikat,NaN,1/2,NaN
7631,3731,"Warszawa, Śródmieście",300000.0,14.00,1,wtórny,2022-06-27,nie,NaN,1/4,garaż/miejsce parkingowe
11304,3504,"Warszawa, Ursus",199000.0,14.00,1,pierwotny,2023,cegła,NaN,1/2,NaN
12757,1057,"Warszawa, mazowieckie",300000.0,14.00,1,wtórny,1902,nie,NaN,1/4,garaż/miejsce parkingowe
12167,467,"Warszawa, Ochota, ul. Baśniowa",315000.0,14.00,1,wtórny,2022-08-01,plastikowe,NaN,1/4,NaN
14998,3298,"Warszawa, Praga-Południe, Grochów",240000.0,12.90,1,wtórny,kamienica,NaN,NaN,NaN,NaN
11303,3503,"Warszawa, Ursus",145000.0,10.00,1,wtórny,2021,cegła,NaN,suterena/3,NaN
20404,4804,"Warszawa, Wola",951000.0,6.00,3,pierwotny,2021,"telewizja kablowa, internet, telefon","balkon, taras",&gt; 10/21,garaż/miejsce parkingowe

In [71]:
data.drop(data.index[-1], axis= 'rows', inplace=True)

In [72]:
data.tail(5)

,Unnamed: 0,Address,Price,Space,Rooms,Market,Year,Evelevator,Balcony,Level,Parking place
11304,3504,"Warszawa, Ursus",199000.0,14.0,1,pierwotny,2023,cegła,NaN,1/2,NaN
12757,1057,"Warszawa, mazowieckie",300000.0,14.0,1,wtórny,1902,nie,NaN,1/4,garaż/miejsce parkingowe
12167,467,"Warszawa, Ochota, ul. Baśniowa",315000.0,14.0,1,wtórny,2022-08-01,plastikowe,NaN,1/4,NaN
14998,3298,"Warszawa, Praga-Południe, Grochów",240000.0,12.9,1,wtórny,kamienica,NaN,NaN,NaN,NaN
11303,3503,"Warszawa, Ursus",145000.0,10.0,1,wtórny,2021,cegła,NaN,suterena/3,NaN

## Rooms

In [73]:
data.Rooms

14362    10
20970     4
7155      4
1687      8
12380     6
         ..
11304     1
12757     1
12167     1
14998     1
11303     1
Name: Rooms, Length: 17064, dtype: int64

In [74]:
data.Rooms.unique()

array([10,  4,  8,  6,  2,  7,  5,  3,  9,  1], dtype=int64)

## Market

In [75]:
data.Market

14362       wtórny
20970       wtórny
7155        wtórny
1687        wtórny
12380       wtórny
           ...
11304    pierwotny
12757       wtórny
12167       wtórny
14998       wtórny
11303       wtórny
Name: Market, Length: 17064, dtype: object

In [76]:
data.Market.unique()

array(['wtórny', 'pierwotny', nan], dtype=object)

In [77]:
data.dropna(subset = ['Market'], axis = 'rows',inplace=True)

In [78]:
data.Market.unique()

array(['wtórny', 'pierwotny'], dtype=object)

## Year

In [79]:
data.Year

14362     kamienica
20970          2015
7155           2015
1687           2005
12380          2021
            ...
11304          2023
12757          1902
12167    2022-08-01
14998     kamienica
11303          2021
Name: Year, Length: 16027, dtype: object

In [99]:
data.Year.unique()

array(['kamienica', '2015', '2005', '2021', '2001', '2022', '1936',
       '2021-05-29', '2002', '2022-07-08', '1995', '2009',
       'apartamentowiec', '2011', '2022-07-01', '2006', '1912', '1911',
       '2022-04-28', '2010', '1910', '2012', '1932', '2016', '1996',
       '1992', '2017', '2021-08-19', '2020', '2000', '2008', '1913',
       'szeregowiec', '2022-04-05', '1914', '2003', '1980-01-01',
       '2021-02-01', '2013', '2021-07-01', '2018', '1939', '2022-05-25',
       '2021-10-04', 'blok', '2007', '2021-10-01', '1999', '2022-06-01',
       '2022-01-21', '2022-05-01', '2022-08-01', '1902', '2004', '1935',
       '2022-01-12', '2022-06-30', '2023', '1997', 'tak', '1998', '2014',
       '2021-09-14', '2022-05-13', '1905', '1930', '2022-05-16',
       '2022-04-30', '1975', '2021-11-03', '2021-07-09', '2023-07-31',
       '2022-05-31', '2022-01-01', '1924', 'drewniane', '2020-09-14',
       '2022-10-15', '1929', '1938', '1904', '1977', '2019', '1990',
       '2023-02-01', '2022-02-07', '2021-12-01', '2023-07-25',
       '2022-11-15', '1927', '1994', '2022-08-10', '1972', '1993',
       '2022-07-05', '1920', '1960', '2022-01-05', '1900', '2022-05-02',
       '2022-03-09', '2022-02-22', '2022-06-02', '2022-06-12',
       '2022-04-11', '2022-06-21', '2022-01-27', '2022-02-24', '1921',
       'dom wolnostojący', '2021-11-29', '2022-01-17', '2024',
       '2024-03-31', '2022-04-01', '1956', '2022-03-01', '2021-12-14',
       '2023-01-09', '1934', '2022-10-31', '2022-09-01', '2022-06-04',
       '2022-04-19', '2022-02-10', '2021-06-01', '2022-06-20',
       '2022-03-04', '2021-11-17', '1950', '1931', '1923', '2023-12-31',
       '2021-11-30', '2021-12-13', '2022-03-31', '2021-08-04', '1988',
       '2023-04-01', '2022-05-05', '2022-03-30', '1980', '2022-04-04',
       '2022-04-10', '2022-01-03', '2022-04-12', '2021-10-06',
       '2021-02-15', '2023-03-30', '2019-05-01', '2021-12-09',
       '2022-02-17', '1890', '2022-04-27', '2022-04-25', '1894',
       'plastikowe', '2021-02-14', '2022-01-15', '2022-03-29',
       '2021-12-20', '2023-10-01', '2021-10-21', '2021-08-31',
       '2022-03-22', '2019-04-05', '2022-07-10', '2021-12-04', '1937',
       '2019-06-01', '2022-05-12', '2022-02-28', '2021-08-01', '1933',
       '2021-11-05', '2020-06-30', '1928', '1949', '2022-08-31', '1985',
       '1973', 'nie', '2022-01-18', '1970', '2022-06-07', '1978', '1979',
       '1955', '1976', '2022-07-07', '2022-05-18', '2022-06-08', '1981',
       '2022-06-28', '2023-10-31', '2021-05-11', '2022-07-15', '1987',
       '2022-05-09', '2022-01-19', '2022-10-16', '2021-11-07',
       '2022-10-08', '2025', '2022-05-22', '2022-06-29', '1917', '1870',
       '2022-02-01', '1906', '2022-03-20', '1958', '2022-05-30',
       '2022-07-27', '2022-07-04', '2022-04-20', '1986', '2023-07-01',
       '2022-06-14', '2022-11-01', '2022-01-10', '2022-05-06', '1966',
       '2022-06-24', '2022-06-18', '2023-01-20', '2021-11-02', '1895',
       '1974', '2022-10-01', '1926', '2022-05-08', '2021-10-10',
       '2022-06-13', '2022-07-06', '2019-07-31', '2022-02-09', '1946',
       '2019-08-01', '2022-06-15', '1982', '2021-09-30', '1983', '1952',
       '2022-06-03', '2022-09-30', '2021-09-16', '2023-03-31',
       '2022-12-19', '2022-05-10', '2022-04-21', '2022-07-29',
       '2022-05-24', '1989', '1880', '2020-10-01', '2022-07-31',
       '2021-10-20', '2021-02-16', '1991', '2022-06-06', '2022-05-20',
       '2022-06-27', '2022-04-08', '2022-07-11', '2022-07-03',
       '2022-12-31', '2021-03-31', '1965', '2022-03-24', '2024-08-30',
       '2021-08-13', '2021-11-01', '1881', '2021-09-15', '2022-01-04',
       '2022-05-27', '1962', '2022-05-23', '2021-09-09', '1954',
       '2022-04-06', '2020-08-01', '2022-05-04', '1951', '2024-10-18',
       '2023-05-15', '2022-04-07', '2022-03-10', '2021-11-09',
       '2022-05-19', '2021-11-23', '2023-09-01', '1984', '1953',
       '2022-02-11', '2023-12-30', '2024-08-31', '2024-01-31',
       '2022-04-29', '2022-04-26', '2022-03-07', '1969', '2022-03-28',
       '2021-04-28', '2022-06-22', '2024-03-01', '2021-04-23',
       '2021-01-10', '1968', '2022-03-17', '2022-02-15', '2021-12-22',
       '2022-02-02', '2024-01-10', '2021-05-01', '2021-06-10', '1925',
       '2021-07-19', '2023-03-01', '2024-09-30', '1', '1957',
       '2022-06-25', '2022-01-25', '2022-06-10', '2022-03-18',
       '2021-10-28', '2023-06-01', '2021-10-19', '2022-07-02', '1200',
       '2019-02-01', '2022-04-22', '2022-06-17', '56', '2021-10-15',
       '1961', '1948', '2021-11-16', '2022-01-11', '2022-05-26',
       '2022-04-23', '2022-06-23', '2022-01-24', '2021-04-30', '1963',
       '2021-11-22', '2022-03-25', '2022-10-03', '2021-12-16',
       '2022-01-31', '2022-07-19', '2020-11-30', '2023-06-15',
       '2022-08-15', '2020-01-01', '2022-06-19', '1964', '2021-10-23',
       '2022-06-16', '2022-02-14', '2023-01-01', '2021-03-10', '1901',
       '2022-08-08', '2022-04-18', '1971', '2021-09-10', '2022-06-09',
       '2021-11-20', '2022-05-28', '2022-10-20', '2022-03-14',
       '2022-02-18', '2022-04-15', '2022-07-20', '2024-02-28',
       '2022-03-13', '2022-02-21', '2021-03-28', '2022-03-21',
       '2022-07-18', '2022-05-21', '2022-07-16', '2022-01-26',
       '2024-12-01', '1922', '2021-09-28', '2922', '2022-12-12',
       '2022-03-15', '2024-02-01', '2022-03-11', '2023-12-27',
       '2022-05-17', '2022-03-06', '2021-09-27', '2021-08-25',
       '2023-06-03', '2022-07-30', '2021-10-11', '2022-02-04',
       '2021-02-09', '2022-01-13', '2023-08-01', '2021-10-13', '1967',
       '2022-02-13', '2021-05-20', '1940', '2022-04-24', '2021-10-12',
       '2021-12-06', '2022-08-30', '2021-09-01', '2022-12-30',
       '2023-07-03', '2021-12-03', '1898', '2022-03-16', '2022-02-03',
       '2022-01-28', '2021-12-08', '2023-06-30', '2022-05-11',
       '2021-10-31', '2022-11-30', '1916', '2022-03-05', '2022-06-11',
       '2024-01-01', '2020-04-04', '2021-12-28', '2024-10-01',
       '2016-10-07', '2021-03-27', '1915', '2023-08-31', '2021-06-05',
       '2021-11-25', '2021-11-15', '2098', '2021-05-07', '1694', '1959',
       '2021-09-21', '2022-06-26', '2023-02-14', '1947', '2018-09-13',
       '2022-05-15', '2022-04-13', '2021-08-24', '2022-02-26',
       '2022-08-06', '2022-05-03', '2021-07-05', '2024-10-09',
       '2022-12-20', '2022-06-05', '2021-04-06', '2021-09-03',
       '2021-10-14', '2021-04-01', '2021-01-31', '2022-01-20',
       '2022-02-25', '2023-11-30', '2022-03-23', '65', '2022-11-10',
       '2022-02-23', '2021-12-10', '2021-12-21', '2022-10-05',
       '2023-02-07', '2023-10-15', '2022-07-12', '2021-12-15', '1944',
       '2022-01-07', '2022-03-02', '2020-01-10', '2021-07-15',
       '2022-09-06', '2020-12-11', '2018-03-01', '19070', '2020-10-17',
       '2021-03-15', '2022-08-03', '2022-07-28', '2022-09-14',
       '2023-12-01', '2021-02-27', 'aluminiowe', '2024-09-20',
       '2024-03-30', '2020-07-01', '2022-08-26', '2023-10-02',
       '2023-09-30', '2022-07-25', '2021-08-17', '2021-08-09',
       '2021-01-25', '2022-12-01', '2021-10-18', '2022-03-08',
       '2022-03-03', '2022-09-15', '2021-08-15', '2023-05-01',
       '2021-11-10', '2024-10-14', '1882', '1919', '2021-03-01',
       '2021-02-25', '2023-01-08', '2022-07-22', '2022-04-14',
       '2021-10-07', '2023-11-01', '2022-08-29', '1897', '2021-12-07',
       '2022-05-14', '50', '2022-02-16', '2021-10-03', '2022-04-16',
       '2022-02-19'], dtype=object)

In [109]:
import re 
data.Year = [re.findall('(\d{4})',x) for x in data.Year]

TypeError: expected string or bytes-like object

In [110]:
data['Year'] = data['Year'].str.get(0)

In [111]:
data.head(5)

,Unnamed: 0,Address,Price,Space,Rooms,Market,Year,elevator,Balcony,Level,Parking place
14362,2662,"Warszawa, Praga-Południe",5520000.0,600.00,10,wtórny,NaN,"telewizja kablowa, internet, telefon","balkon, ogródek, taras",3/3,garaż/miejsce parkingowe
20970,5370,"Warszawa, Wawer, ul. Patriotów",4000000.0,560.00,4,wtórny,2015,tak,"balkon, ogródek, taras",3/3,garaż/miejsce parkingowe
7155,3255,"Warszawa, Wawer, ul. Patriotów",4000000.0,560.00,4,wtórny,2015,tak,"balkon, ogródek, taras",3/3,garaż/miejsce parkingowe
1687,1687,"Warszawa, Wilanów, Sarmacka",7600000.0,497.00,8,wtórny,2005,nie,"balkon, ogródek, taras",NaN,garaż/miejsce parkingowe
16202,602,"Warszawa, Śródmieście, Powiśle, Elektryczna",21350100.0,487.75,10,wtórny,2021,tak,taras,6/6,garaż/miejsce parkingowe

In [112]:
data.dropna(subset = ['Year'], axis = 'rows',inplace=True)

## Elevator

In [80]:
len(data.Evelevator.unique())

100

In [81]:
round(data.Evelevator.isna().sum() / len(data.Evelevator),2)

0.11

In [82]:
data.dropna(subset = ['Evelevator'], axis = 'rows',inplace=True)

In [95]:
data = data.rename({'Evelevator': 'elevator'}, axis=1)

In [96]:
data.head(1)

,Unnamed: 0,Address,Price,Space,Rooms,Market,Year,elevator,Balcony,Level,Parking place
14362,2662,"Warszawa, Praga-Południe",5520000.0,600.0,10,wtórny,kamienica,"telewizja kablowa, internet, telefon","balkon, ogródek, taras",3/3,garaż/miejsce parkingowe

In [115]:
data = data[(data['elevator'] == 'tak') | (data['elevator'] == 'nie')]

## Balcony

In [117]:
data.Balcony

20970    balkon, ogródek, taras
7155     balkon, ogródek, taras
1687     balkon, ogródek, taras
16202                     taras
2504                      taras
                  ...
4299                        NaN
4501                        NaN
7888                        NaN
7631                        NaN
12757                       NaN
Name: Balcony, Length: 7677, dtype: object

In [118]:
data.dropna(subset = ['Balcony'], axis = 'rows',inplace=True)

In [120]:
data.Balcony.unique()

array(['balkon, ogródek, taras', 'taras', 'balkon, taras', 'balkon',
       'ogródek, taras', 'ogródek', 'balkon, ogródek'], dtype=object)

I will change this column into three new binary feature. Balkon, taras, ogródek.

In [134]:
balkon = [1 if x == 'balkon, ogródek, taras' else 0 if  x =='balkon, taras' else 0 if x =='balkon' else 0   if x =='balkon, ogródek' else 0 for x in data.Balcony]
taras = [1 if x == 'balkon, ogródek, taras' else 0 if  x =='balkon, taras' else 0 if x =='taras' else 0   if x == 'ogródek, taras' else 0 for x in data.Balcony]
ogródek = [1 if x == 'balkon, ogródek, taras' else 0 if  x =='balkon, ogródek' else 0 if x =='ogródek' else 0   if x =='taras, ogródek' else 0 for x in data.Balcony]

In [135]:
data['balkon'] = balkon
data['taras'] = taras
data['ogródek'] = ogródek

In [141]:
data.head(4)

,Unnamed: 0,Address,Price,Space,Rooms,Market,Year,elevator,Balcony,Level,Parking place,balkon,taras,ogródek
20970,5370,"Warszawa, Wawer, ul. Patriotów",4000000.0,560.00,4,wtórny,2015,1,"balkon, ogródek, taras",3/3,1,1,1,1
7155,3255,"Warszawa, Wawer, ul. Patriotów",4000000.0,560.00,4,wtórny,2015,1,"balkon, ogródek, taras",3/3,1,1,1,1
1687,1687,"Warszawa, Wilanów, Sarmacka",7600000.0,497.00,8,wtórny,2005,0,"balkon, ogródek, taras",NaN,1,1,1,1
16202,602,"Warszawa, Śródmieście, Powiśle, Elektryczna",21350100.0,487.75,10,wtórny,2021,1,taras,6/6,1,0,0,0

In [144]:
data.drop(['Balcony'], axis = 1,inplace = True)

## Parking place

In [121]:
data['Parking place']

20970    garaż/miejsce parkingowe
7155     garaż/miejsce parkingowe
1687     garaż/miejsce parkingowe
16202    garaż/miejsce parkingowe
2504     garaż/miejsce parkingowe
                   ...
8182                          NaN
23187    garaż/miejsce parkingowe
11737    garaż/miejsce parkingowe
657      garaż/miejsce parkingowe
538      garaż/miejsce parkingowe
Name: Parking place, Length: 6125, dtype: object

In [122]:
data['Parking place'].unique()

array(['garaż/miejsce parkingowe', nan], dtype=object)

In [124]:
data['Parking place'] = data['Parking place'].replace([np.NAN], 0)
data['Parking place'] = data['Parking place'].replace(['garaż/miejsce parkingowe'], 1)

In [125]:
data['Parking place']

20970    1
7155     1
1687     1
16202    1
2504     1
        ..
7982     1
23187    1
11737    1
657      1
538      1
Name: Parking place, Length: 3795, dtype: int64

## Adress

In [146]:
data.head(5)

,Unnamed: 0,Address,Price,Space,Rooms,Market,Year,elevator,Level,Parking place,balkon,taras,ogródek
20970,5370,"Warszawa, Wawer, ul. Patriotów",4000000.0,560.00,4,wtórny,2015,1,3/3,1,1,1,1
7155,3255,"Warszawa, Wawer, ul. Patriotów",4000000.0,560.00,4,wtórny,2015,1,3/3,1,1,1,1
1687,1687,"Warszawa, Wilanów, Sarmacka",7600000.0,497.00,8,wtórny,2005,0,NaN,1,1,1,1
16202,602,"Warszawa, Śródmieście, Powiśle, Elektryczna",21350100.0,487.75,10,wtórny,2021,1,6/6,1,0,0,0
2504,2504,"Warszawa, Mokotów, Cybulskiego",19900000.0,487.00,6,wtórny,2001,1,5/5,1,0,0,0

In [145]:
data.Address

20970                    Warszawa, Wawer, ul. Patriotów
7155                     Warszawa, Wawer, ul. Patriotów
1687                        Warszawa, Wilanów, Sarmacka
16202       Warszawa, Śródmieście, Powiśle, Elektryczna
2504                     Warszawa, Mokotów, Cybulskiego
                              ...
7982     Warszawa, Ursynów, ul. rtm. Witolda Pileckiego
23187                                 Warszawa, Ursynów
11737                       Warszawa, Ursynów, Puławska
657      Warszawa, Ursynów, ul. rtm. Witolda Pileckiego
538      Warszawa, Ursynów, ul. rtm. Witolda Pileckiego
Name: Address, Length: 3795, dtype: object

In [152]:
warsaw_districts = ['Wawer', 'Wilanów','Powiśle', 'Mokotów', 'Ursynów','Aleksandrów', 'Bemowo','Białołeka',
 'Bielany', 'Centrum','Metro Wilanowska', 'Ochota', 'Praga-Północ','Praga-Południe', 'Rembertów', 'Śródmieście', 'Targówek',
 'Ursus','Wesoła','Włochy','Żoliborz', 'Wola']

adr = data.Address.str.replace('Warszawa,', '')
[if x is in warsaw_districts else None for x in adr ]

20970                     Wawer, ul. Patriotów
7155                      Wawer, ul. Patriotów
1687                         Wilanów, Sarmacka
16202        Śródmieście, Powiśle, Elektryczna
2504                      Mokotów, Cybulskiego
                         ...
7982      Ursynów, ul. rtm. Witolda Pileckiego
23187                                  Ursynów
11737                        Ursynów, Puławska
657       Ursynów, ul. rtm. Witolda Pileckiego
538       Ursynów, ul. rtm. Witolda Pileckiego
Name: Address, Length: 3795, dtype: object

In [ ]:
district = data
district = data

In [ ]:
data['district']
data['street']
data['number']

## export

In [ ]:
data.to_csv('data/data_clean_removed')