In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('data/data_clean_removed.csv')

In [3]:
data.head(5)

,Unnamed: 0,Price,Space,Rooms,Market,Year,elevator,Parking place,balkon,taras,ogródek,district,street,level,max_level
0,20970,4000000.0,560.00,4,wtórny,2015,1,1,1,1,1,Wawer,Patriotów,3,3
1,7155,4000000.0,560.00,4,wtórny,2015,1,1,1,1,1,Wawer,Patriotów,3,3
2,16202,21350100.0,487.75,10,wtórny,2021,1,1,0,0,0,Śródmieście,Elektryczna,6,6
3,2504,19900000.0,487.00,6,wtórny,2001,1,1,0,0,0,Mokotów,Cybulskiego,5,5
4,9677,795900.0,445.00,2,pierwotny,2022,1,1,0,0,0,Praga-Południe,Gocław,4,8

In [4]:
from pycaret.regression import *
setup = setup(data, target = 'Price')

In [5]:
best = compare_models()

In [6]:
evaluate_model(best)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Hyperparameters', 'param…