In [116]:
from selenium import webdriver
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [117]:
driver = webdriver.Chrome("C:/Users/ja/Desktop/python/chromedriver")
#page = driver.get("https://www.otodom.pl/pl/oferty/sprzedaz/mieszkanie/warszawa")

page_url = 'https://www.otodom.pl/pl/oferty/sprzedaz/mieszkanie/warszawa'
page = requests.get(page_url)

<ipython-input-117-e0ef3de0182e>:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome("C:/Users/ja/Desktop/python/chromedriver")

In [118]:
content = page.content
soup = BeautifulSoup(content, features='html.parser')

span =soup.find_all('span')
print(len(span))

263

In [119]:
spans = soup.find_all("span", class_="css-rmqm02 eclomwz0")
addreses = soup.find_all("span", class_="css-17o293g es62z2j9")
spans[:4]

[<span class="css-rmqm02 eclomwz0">541 000 zł</span>,
 <span class="css-rmqm02 eclomwz0"><strong>15 912 zł/m²</strong></span>,
 <span class="css-rmqm02 eclomwz0">1 pokój</span>,
 <span class="css-rmqm02 eclomwz0">34 m²</span>]

In [120]:
addreses

[<span class="css-17o293g es62z2j9">Warszawa, Praga-Południe, Szaserów 48</span>,
 <span class="css-17o293g es62z2j9">Warszawa, Ursus, ul. Konotopska</span>,
 <span class="css-17o293g es62z2j9">Warszawa, Mokotów, ul. Augustówka</span>,
 <span class="css-17o293g es62z2j9">Warszawa, Ursynów</span>,
 <span class="css-17o293g es62z2j9">Warszawa, Mokotów</span>,
 <span class="css-17o293g es62z2j9">Warszawa, Bielany, Stare Bielany, Jana Kasprowicza</span>,
 <span class="css-17o293g es62z2j9">Warszawa, Praga-Północ, ul. Grodzieńska</span>,
 <span class="css-17o293g es62z2j9">Warszawa, Ursynów, Gawota</span>,
 <span class="css-17o293g es62z2j9">Warszawa, Ochota, Rakowiec, ul. Jasielska</span>,
 <span class="css-17o293g es62z2j9">Warszawa, Bemowo</span>,
 <span class="css-17o293g es62z2j9">Warszawa, Mokotów, Służewiec</span>,
 <span class="css-17o293g es62z2j9">Warszawa, Ursynów, ul. Batystowa</span>,
 <span class="css-17o293g es62z2j9">Warszawa, Praga-Południe</span>,
 <span class="css-17o293g es62z2j9">Warszawa, Targówek, Bródno</span>,
 <span class="css-17o293g es62z2j9">Warszawa, Śródmieście, Śródmieście Południowe, Piękna</span>,
 <span class="css-17o293g es62z2j9">Warszawa, Ursynów, ul. Batystowa</span>,
 <span class="css-17o293g es62z2j9">Warszawa, Ursus, ul. Skoroszewska</span>,
 <span class="css-17o293g es62z2j9">Warszawa, Mokotów, Aleja Wilanowska</span>,
 <span class="css-17o293g es62z2j9">Warszawa, Wilanów, Herbu Janina</span>,
 <span class="css-17o293g es62z2j9">Warszawa, Ursus, ul. Dzieci Warszawy</span>,
 <span class="css-17o293g es62z2j9">Warszawa, Targówek, Zacisze, ul. Lewinowska</span>,
 <span class="css-17o293g es62z2j9">Warszawa, Śródmieście, al. Aleja Niepodległości</span>,
 <span class="css-17o293g es62z2j9">Warszawa, Śródmieście, ul. Wspólna</span>,
 <span class="css-17o293g es62z2j9">Warszawa, Mokotów, ul. Wiktorska</span>,
 <span class="css-17o293g es62z2j9">Warszawa, Ochota</span>,
 <span class="css-17o293g es62z2j9">Warszawa, Wola</span>,
 <span class="css-17o293g es62z2j9">Warszawa, Praga-Północ, ul. Tadeusza Korsaka</span>,
 <span class="css-17o293g es62z2j9">Warszawa, Białołęka, ul. Duninów</span>,
 <span class="css-17o293g es62z2j9">Warszawa, Mokotów, ul. Wołoska</span>,
 <span class="css-17o293g es62z2j9">Warszawa, Wola, ul. Sławińska</span>,
 <span class="css-17o293g es62z2j9">Warszawa, Wola, ul. Sławińska</span>,
 <span class="css-17o293g es62z2j9">Warszawa, Wola, ul. Sławińska</span>,
 <span class="css-17o293g es62z2j9">Warszawa, Wola, ul. Sławińska</span>,
 <span class="css-17o293g es62z2j9">Warszawa, Wola, ul. Sławińska</span>,
 <span class="css-17o293g es62z2j9">Warszawa, Ochota, Rakowiec</span>,
 <span class="css-17o293g es62z2j9">Warszawa, Białołęka, ul. Duninów</span>,
 <span class="css-17o293g es62z2j9">Warszawa, Białołęka, ul. Duninów</span>,
 <span class="css-17o293g es62z2j9">Warszawa, Mokotów, Giordana Bruna</span>,
 <span class="css-17o293g es62z2j9">Warszawa, Bemowo, ul. Wieśniacza</span>]

In [121]:
spans[3:9]

[<span class="css-rmqm02 eclomwz0">34 m²</span>,
 <span class="css-rmqm02 eclomwz0">675 000 zł</span>,
 <span class="css-rmqm02 eclomwz0"><strong>12 500 zł/m²</strong></span>,
 <span class="css-rmqm02 eclomwz0">3 pokoje</span>,
 <span class="css-rmqm02 eclomwz0">54 m²</span>,
 <span class="css-rmqm02 eclomwz0">545 000 zł</span>]

In [122]:
price = spans[::4]
rooms = spans[2::4]
space = spans[3::4]

In [123]:
for p in price:
    print(str(p))

<span class="css-rmqm02 eclomwz0">541 000 zł</span>
<span class="css-rmqm02 eclomwz0">675 000 zł</span>
<span class="css-rmqm02 eclomwz0">545 000 zł</span>
<span class="css-rmqm02 eclomwz0">999 000 zł</span>
<span class="css-rmqm02 eclomwz0">2 225 300 zł</span>
<span class="css-rmqm02 eclomwz0">818 080 zł</span>
<span class="css-rmqm02 eclomwz0">399 999 zł</span>
<span class="css-rmqm02 eclomwz0">1 560 000 zł</span>
<span class="css-rmqm02 eclomwz0">375 000 zł</span>
<span class="css-rmqm02 eclomwz0">444 000 zł</span>
<span class="css-rmqm02 eclomwz0">474 700 zł</span>
<span class="css-rmqm02 eclomwz0">Zapytaj o cenę</span>
<span class="css-rmqm02 eclomwz0">893 730 zł</span>
<span class="css-rmqm02 eclomwz0">935 000 zł</span>
<span class="css-rmqm02 eclomwz0">1 499 000 zł</span>
<span class="css-rmqm02 eclomwz0">Zapytaj o cenę</span>
<span class="css-rmqm02 eclomwz0">577 100 zł</span>
<span class="css-rmqm02 eclomwz0">685 000 zł</span>
<span class="css-rmqm02 eclomwz0">1 590 000 zł</span>
<span class="css-rmqm02 eclomwz0">830 000 zł</span>
<span class="css-rmqm02 eclomwz0">439 000 zł</span>
<span class="css-rmqm02 eclomwz0">339 000 zł</span>
<span class="css-rmqm02 eclomwz0">1 189 000 zł</span>
<span class="css-rmqm02 eclomwz0">740 000 zł</span>
<span class="css-rmqm02 eclomwz0">480 000 zł</span>
<span class="css-rmqm02 eclomwz0">599 999 zł</span>
<span class="css-rmqm02 eclomwz0">599 999 zł</span>
<span class="css-rmqm02 eclomwz0">Zapytaj o cenę</span>
<span class="css-rmqm02 eclomwz0">640 000 zł</span>
<span class="css-rmqm02 eclomwz0">762 000 zł</span>
<span class="css-rmqm02 eclomwz0">550 000 zł</span>
<span class="css-rmqm02 eclomwz0">2 469 000 zł</span>
<span class="css-rmqm02 eclomwz0">1 306 000 zł</span>
<span class="css-rmqm02 eclomwz0">1 459 000 zł</span>
<span class="css-rmqm02 eclomwz0">390 000 zł</span>
<span class="css-rmqm02 eclomwz0">Zapytaj o cenę</span>
<span class="css-rmqm02 eclomwz0">Zapytaj o cenę</span>
<span class="css-rmqm02 eclomwz0">628 000 zł</span>
<span class="css-rmqm02 eclomwz0">Zapytaj o cenę</span>

In [124]:
import re

def clean(raw_html):
    cleanr = re.compile('<.*?>')
    cleantext  = re.sub(cleanr, '', str(raw_html))
    cleantext= re.sub("[^0-9]", "", cleantext)
    return cleantext 

cleaned_price = []

for p in price:
    cleaned = clean(p)
    cleaned_price.append(cleaned)
    
cleaned_price

['541000',
 '675000',
 '545000',
 '999000',
 '2225300',
 '818080',
 '399999',
 '1560000',
 '375000',
 '444000',
 '474700',
 '',
 '893730',
 '935000',
 '1499000',
 '',
 '577100',
 '685000',
 '1590000',
 '830000',
 '439000',
 '339000',
 '1189000',
 '740000',
 '480000',
 '599999',
 '599999',
 '',
 '640000',
 '762000',
 '550000',
 '2469000',
 '1306000',
 '1459000',
 '390000',
 '',
 '',
 '628000',
 '']

In [125]:
cleaned_rooms =[]

for r in rooms:
    cleaned = clean(r)
    cleaned_rooms.append(cleaned)
cleaned_rooms

['1',
 '3',
 '2',
 '3',
 '5',
 '3',
 '1',
 '5',
 '1',
 '2',
 '2',
 '3',
 '3',
 '3',
 '2',
 '5',
 '3',
 '3',
 '4',
 '3',
 '2',
 '2',
 '3',
 '2',
 '2',
 '3',
 '2',
 '4',
 '2',
 '2',
 '1',
 '5',
 '3',
 '4',
 '1',
 '2',
 '3',
 '1',
 '3']

In [126]:
space

[<span class="css-rmqm02 eclomwz0">34 m²</span>,
 <span class="css-rmqm02 eclomwz0">54 m²</span>,
 <span class="css-rmqm02 eclomwz0">37.4 m²</span>,
 <span class="css-rmqm02 eclomwz0">101.3 m²</span>,
 <span class="css-rmqm02 eclomwz0">117.79 m²</span>,
 <span class="css-rmqm02 eclomwz0">51.13 m²</span>,
 <span class="css-rmqm02 eclomwz0">26.91 m²</span>,
 <span class="css-rmqm02 eclomwz0">146.14 m²</span>,
 <span class="css-rmqm02 eclomwz0">26.5 m²</span>,
 <span class="css-rmqm02 eclomwz0">33.5 m²</span>,
 <span class="css-rmqm02 eclomwz0">39.07 m²</span>,
 <span class="css-rmqm02 eclomwz0">59.79 m²</span>,
 <span class="css-rmqm02 eclomwz0">57.66 m²</span>,
 <span class="css-rmqm02 eclomwz0">69 m²</span>,
 <span class="css-rmqm02 eclomwz0">59.47 m²</span>,
 <span class="css-rmqm02 eclomwz0">129.82 m²</span>,
 <span class="css-rmqm02 eclomwz0">58.33 m²</span>,
 <span class="css-rmqm02 eclomwz0">57.5 m²</span>,
 <span class="css-rmqm02 eclomwz0">89 m²</span>,
 <span class="css-rmqm02 eclomwz0">86.2 m²</span>,
 <span class="css-rmqm02 eclomwz0">42.2 m²</span>,
 <span class="css-rmqm02 eclomwz0">29 m²</span>,
 <span class="css-rmqm02 eclomwz0">69 m²</span>,
 <span class="css-rmqm02 eclomwz0">49.62 m²</span>,
 <span class="css-rmqm02 eclomwz0">38.3 m²</span>,
 <span class="css-rmqm02 eclomwz0">46.78 m²</span>,
 <span class="css-rmqm02 eclomwz0">47 m²</span>,
 <span class="css-rmqm02 eclomwz0">83.81 m²</span>,
 <span class="css-rmqm02 eclomwz0">48.7 m²</span>,
 <span class="css-rmqm02 eclomwz0">42.65 m²</span>,
 <span class="css-rmqm02 eclomwz0">29.79 m²</span>,
 <span class="css-rmqm02 eclomwz0">112.91 m²</span>,
 <span class="css-rmqm02 eclomwz0">66.99 m²</span>,
 <span class="css-rmqm02 eclomwz0">83.45 m²</span>,
 <span class="css-rmqm02 eclomwz0">18.3 m²</span>,
 <span class="css-rmqm02 eclomwz0">44.39 m²</span>,
 <span class="css-rmqm02 eclomwz0">50.38 m²</span>,
 <span class="css-rmqm02 eclomwz0">37.5 m²</span>,
 <span class="css-rmqm02 eclomwz0">58.34 m²</span>]

In [138]:
cleaned_space =[]

for s in space:
    s = str(s)
    cleaned_space.append(s[34:40].replace('m','').replace('<',"").replace('²','').replace(' ',''))

cleaned_space

['34',
 '54',
 '37.4',
 '101.3',
 '117.79',
 '51.13',
 '26.91',
 '146.14',
 '26.5',
 '33.5',
 '39.07',
 '59.79',
 '57.66',
 '69',
 '59.47',
 '129.82',
 '58.33',
 '57.5',
 '89',
 '86.2',
 '42.2',
 '29',
 '69',
 '49.62',
 '38.3',
 '46.78',
 '47',
 '83.81',
 '48.7',
 '42.65',
 '29.79',
 '112.91',
 '66.99',
 '83.45',
 '18.3',
 '44.39',
 '50.38',
 '37.5',
 '58.34']

In [141]:
df = pd.DataFrame({'Address': addreses, 'Price': cleaned_price, 'Space': cleaned_space, 'Rooms': cleaned_rooms})
df

                                              Address    Price   Space Rooms
0             [Warszawa, Praga-Południe, Szaserów 48]   541000      34     1
1                   [Warszawa, Ursus, ul. Konotopska]   675000      54     3
2                 [Warszawa, Mokotów, ul. Augustówka]   545000    37.4     2
3                                 [Warszawa, Ursynów]   999000   101.3     3
4                                 [Warszawa, Mokotów]  2225300  117.79     5
5   [Warszawa, Bielany, Stare Bielany, Jana Kaspro...   818080   51.13     3
6           [Warszawa, Praga-Północ, ul. Grodzieńska]   399999   26.91     1
7                         [Warszawa, Ursynów, Gawota]  1560000  146.14     5
8         [Warszawa, Ochota, Rakowiec, ul. Jasielska]   375000    26.5     1
9                                  [Warszawa, Bemowo]   444000    33.5     2
10                     [Warszawa, Mokotów, Służewiec]   474700   39.07     2
11                 [Warszawa, Ursynów, ul. Batystowa]            59.79     3
12                         [Warszawa, Praga-Południe]   893730   57.66     3
13                       [Warszawa, Targówek, Bródno]   935000      69     3
14  [Warszawa, Śródmieście, Śródmieście Południowe...  1499000   59.47     2
15                 [Warszawa, Ursynów, ul. Batystowa]           129.82     5
16                [Warszawa, Ursus, ul. Skoroszewska]   577100   58.33     3
17              [Warszawa, Mokotów, Aleja Wilanowska]   685000    57.5     3
18                  [Warszawa, Wilanów, Herbu Janina]  1590000      89     4
19             [Warszawa, Ursus, ul. Dzieci Warszawy]   830000    86.2     3
20      [Warszawa, Targówek, Zacisze, ul. Lewinowska]   439000    42.2     2
21  [Warszawa, Śródmieście, al. Aleja Niepodległości]   339000      29     2
22               [Warszawa, Śródmieście, ul. Wspólna]  1189000      69     3
23                 [Warszawa, Mokotów, ul. Wiktorska]   740000   49.62     2
24                                 [Warszawa, Ochota]   480000    38.3     2
25                                   [Warszawa, Wola]   599999   46.78     3
26     [Warszawa, Praga-Północ, ul. Tadeusza Korsaka]   599999      47     2
27                 [Warszawa, Białołęka, ul. Duninów]            83.81     4
28                   [Warszawa, Mokotów, ul. Wołoska]   640000    48.7     2
29                    [Warszawa, Wola, ul. Sławińska]   762000   42.65     2
30                    [Warszawa, Wola, ul. Sławińska]   550000   29.79     1
31                    [Warszawa, Wola, ul. Sławińska]  2469000  112.91     5
32                    [Warszawa, Wola, ul. Sławińska]  1306000   66.99     3
33                    [Warszawa, Wola, ul. Sławińska]  1459000   83.45     4
34                       [Warszawa, Ochota, Rakowiec]   390000    18.3     1
35                 [Warszawa, Białołęka, ul. Duninów]            44.39     2
36                 [Warszawa, Białołęka, ul. Duninów]            50.38     3
37                [Warszawa, Mokotów, Giordana Bruna]   628000    37.5     1
38                 [Warszawa, Bemowo, ul. Wieśniacza]            58.34     3